# Generated by Django 3.2.15 on 2022-09-27 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name1', models.CharField(max_length=15)),
                ('img1', models.ImageField(upload_to='p1')),
                ('dicr1', models.TextField()),
            ],
        ),
    ]
